In [2]:
import spacy
import pandas as pd
nlp = spacy.load("es_core_news_md")

Pre procesamiento

In [9]:
def limpieza(textos):
    resultados = []
    textos = [t.lower() for t in textos]

    for doc in nlp.pipe(textos, batch_size=1000):
        palabras = []
        for token in doc:
            # conservar nombres propios (PROPN)
            if token.pos_ == "PROPN":
                palabras.append(token.text)
                continue
            # permitir palabras alfabéticas, pero no stopwords
            if token.is_alpha and not token.is_stop:
                palabras.append(token.lemma_)
        resultados.append(palabras)
    return resultados

In [4]:
data = pd.read_csv('../data/news_dataset.zip', compression='zip') 
data.head()

,text,label,text_es
0,"Here s the fake black guy, Shaun King weighing...",0,"Aquí está el falso negro, Shaun King, pensando..."
1,A Tennessee Trump supporter is ecstatic that O...,0,Una defensora de Tennessee Trump está extasiad...
2,Join Patrick every week here at 21WIRE.TV for ...,0,Únete a Patrick cada semana aquí en 21WIRE.TV ...
3,This is what happens when racists don t get th...,0,Esto es lo que sucede cuando los racistas no c...
4,WASHINGTON (Reuters) - U.S. President Donald T...,1,WASHINGTON (Reuters) - El presidente estadouni...

In [5]:
#Buscar nulos y duplicados 
print("Nulos:\n",data.isnull().sum())
print("Duplicados: ",data.duplicated().sum())

#Eliminar duplicados 
data.drop_duplicates(inplace=True) 
print("Duplicados: ",data.duplicated().sum())

Nulos:
 text       0
label      0
text_es    0
dtype: int64
Duplicados:  0
Duplicados:  0

In [10]:
#Procesar en chunks 
chunk_size = 5000  # Cambia según tu RAM
textos = list(data['text_es'])
limpiar_textos = []

print("Procesando textos en chunks")
for i in range(0, len(textos), chunk_size):
    chunk = textos[i:i+chunk_size]
    limpiar_chunk = limpieza(chunk)
    limpiar_textos.extend(limpiar_chunk)
#Aplicar limpieza
print(limpiar_textos[:5])

Procesando textos en chunks
[['falso', 'negro', 'shaun', 'king', 'pensar', 'impresionante', 'bernie', 'sander', 'salir', 'armario', 'socialista', 'estados', 'unidos', 'listo', 'abrazar', 'socialista', 'shaun', 'pensar', '/', 'shaunking', 'pregunta', 'janie', 'inferior', 'asalariado', 'pagar', 'cero', 'impuesto', 'justo', 'querer', 'sistema', 'tributario?#demdebate', 'janie', 'johnson', '@jjautor', 'octubre', 'weknown', 'best', 'corredor', 'satisfecho', 'plantearar', 'suficiente', 'pregunta', 'divisiva', 'candidato'], ['defensora', 'tennessee', 'trump', 'extasiado', 'obamacare', 'reducir', 'drásticamente', 'costo', 'seguro', 'familia', 'crédito', 'ley', 'cuidado', 'asequible', 'fortuna', 'familia', 'dio', 'trump', 'mccomic', 'hijo', 'recientemente', 'perder', 'trabajo', 'gracias', 'trumpcare', 'prima', 'caer', 'mes', 'bendición', 'dios', 'regalo', 'führer', 'donald', 'trump', 'crédito', 'fiscal.el', 'washington', 'post', 'señalar', 'cambio', 'precio', 'realidad', 'gracias', 'subsidio', 'ex', 'presidente', 'barack', 'obama', 's', 'affordable', 'care', 'act', 'vigor', 'crédito', 'fiscal', 'propuesto', 'republicano', 'proyecto', 'salud', 'congreso.claro', 'aca', 'aprobar', 'trump', 'considerar', 'postular él', 'presidente', 'ley', 'cuidado', 'salud', 'despojar', 'millón', 'familia', 'bajo', 'ingreso', 'necesitar', 'cubrir', 'mayoría', 'país', 'parecer', 'ee.uu', 'gobierno', 'ee.uu', 'ee.uu', 'importar'], ['únetir', 'patrick', 'semana', '21wire.tv', 'obtener', 'noticia', 'opinión', 'análisis', 'principal', 'historia', 'país', 'extranjero', 'semana', 'episodio', 'orden', 'mundial', 'recuperar', 'bretaña', 'control', 'antiguo', 'colonia', 'americana', 'sigilo', 'cecil', 'rhodes', 'mesa', 'redondo', 'h.g', 'wells', 'henry', 'kissinger', 'zbigniew', 'brzezinski', 'trabajar', 'dirigir', 'mundo', 'allá', 'nacional', 'moderno', 'technetronic', 'gobierno', 'global', 'fin?host', 'patrick', 'henningsen', 'stone', 'autor', 'libro', 'new', 'world', 'order', 'strategy', 'for', 'imperialism', 'escuchar', 'end', 'descargar', 'link', 'start', 'descargar', 'link', 'descargar', 'link', 'descargar', 'podcast', 'end', 'descargar', 'link', 'programa', 'transmitir', 'vivo', 'miércoles', 'noche', 'pm', 'pm', 'mst', 'justo', 'nación', 'savage', 'charla', 'independiente', 'kfnx', 'banda', 'terrestre', 'am', 'región', 'phoenix', 'centro', 'arizona', 'vivo', 'satélite', 'vía', 'www.1100kfnx.com'], ['suceder', 'racista', 'donald', 'trump', 'enfureceír', 'base', 'racista', 'incluir', 'iowa', 'gop', 'rep', 'steve', 'king.el', 'miércoles', 'demócrata', 'anunciar', 'llegar', 'trump', 'revivir', 'programa', 'acción', 'diferido', 'llegada', 'infancia', 'puesto', 'marcha', 'presidente', 'obama', 'impedir', 'deportación', 'persona', 'llevar', 'estados', 'unidos', 'niño', 'padre', 'trump', 'rechazar', 'programa', 'base', 'conservador', 'aplaudir', 'resto', 'nación', 'expresar', 'revulsión.pero', 'trump', 'tema', 'congreso', 'abrir', 'puerta', 'acción', 'legislativo', 'salvar', 'senador', 'chuck', 'schumer', 'rep', 'nancy', 'pelosi', 'ofrecer', 'trump', 'daca', 'restablecer', 'consagrar', 'ley', 'trump', 'seguridad', 'fronterizo', 'incluir', 'muro', 'inútil.trump', 'tomar', 'conservador', 'furiosos.de', 'steve', 'king', 'oficina', 'cnn', 'quejar él', 'ley', 'ee'], ['washington', 'reuters', 'presidente', 'estadounidense', 'donald', 'trump', 'firmar', 'jueves', 'directiva', 'pedir', 'investigación', 'rápido', 'importación', 'acero', 'fabricado', 'extranjero', 'perjudicar', 'seguridad', 'nacional', 'estados', 'unidos', 'funcionario', 'administración', 'trump', 'firmar', 'memorando', 'relacionado', 'sección', 'ley', 'expansión', 'comercial', 'evento', 'casa', 'blanco', 'esperar', 'incluir', 'líder', 'compañía', 'siderúrgico', 'estadounidense', 'ley', 'permitir', 'presidente', 'imponer', 'restricción', 'importación', 'razón', 'seguridad', 'nacional', 'implicación', 'seguridad', 'nacional', 'funcionario', 'importación', 'aleación', 'acero', 'utilizar', 'producto', 'blindaje', 'buque', 'requerir', 'experiencia', 'crear', 'producir', 'secretario', 'comercio', 'wilbur', 'ross', 'lanzar', 'sonda', 'miércoles', 'noche', 'directiva', 'trump', 'pedir', 'ross', 'llevar', 'cabo', 'velocidad', 'deliberado', 'dar', 'resultado', 'presidente', 'recomendación', 'funcionario']]

In [11]:
textos_limpios_str = [" ".join(tokens) for tokens in limpiar_textos]

In [12]:
data_limpio = pd.DataFrame({
    'text_limpio': textos_limpios_str,
    'label': data['label'].values
})
data_limpio.to_csv("../data/dataset_limpio.csv", index=False, encoding='utf-8')
data_limpio.head()

                                         text_limpio  label
0  falso negro shaun king pensar impresionante be...      0
1  defensora tennessee trump extasiado obamacare ...      0
2  únetir patrick semana 21wire.tv obtener notici...      0
3  suceder racista donald trump enfureceír base r...      0
4  washington reuters presidente estadounidense d...      1