In [1]:
import spacy
import pandas as pd
import re
nlp = spacy.load("es_core_news_md")

Pre procesamiento

In [10]:
STOPWORDS_EXTRA = {
    "co", "pic", "amp", "via", "rt", "https", 
    "tuit", "fb", "dw", "cnn", "com", "uu"
}

def limpiar_repeticiones_frases(texto):
    texto = re.sub(r'\b(\w+\s+\w+)(?:\s+\1)+\b', r'\1', texto)
    texto = re.sub(r'\b(\w+)(?:\s+\1)+\b', r'\1', texto)
    return texto

def eliminar_repeticiones_post(tokens):
    resultado = []
    i = 0
    while i < len(tokens):
        if i > 0 and tokens[i] == tokens[i-1]:
            i += 1
            continue
        if i >= 2 and tokens[i-1] == tokens[i-3] and tokens[i] == tokens[i-2]:
            i += 1
            continue
        resultado.append(tokens[i])
        i += 1
    return resultado

def limpieza(textos):
    resultados = []
    textos = [limpiar_repeticiones_frases(t.lower()) for t in textos]

    for doc in nlp.pipe(textos, batch_size=1000):
        palabras = []
        tokens = list(doc)
        i = 0

        while i < len(tokens):
            tok = tokens[i].text
            lemma = tokens[i].lemma_

            if "http" in tok:
                i += 1
                continue
            if "@" in tok:  
                i += 1
                continue
            if tok in ["ee", "ee.", "ee.uu", "eeuu", "ee.uu.", "uu", "uu.","ee.uu.uu"]:
                i += 1
                continue
            if len(tok) == 1 or len(lemma) == 1:
                i += 1
                continue
            if tokens[i].pos_ == "PROPN":
                if tok.lower() not in ["el", "la", "lo"] and tok.lower() not in STOPWORDS_EXTRA:
                    palabras.append(tok)
                i += 1
                continue
            if tokens[i].is_alpha and not tokens[i].is_stop:
                lemma_i = tokens[i].lemma_
                tok_i = tokens[i].text
                if lemma_i in STOPWORDS_EXTRA:
                    i += 1
                    continue
                if tok_i in STOPWORDS_EXTRA:
                    i += 1
                    continue
                if len(lemma_i) == 2:
                    if lemma_i not in ["ee", "uu"]:
                        palabras.append(lemma_i)
                    i += 1
                    continue
                if len(lemma_i) > 2:
                    palabras.append(lemma_i)
            i += 1
        palabras = eliminar_repeticiones_post(palabras)
        palabras = [p for p in palabras if len(p) > 1]
        resultados.append(palabras)
    return resultados

In [9]:
data = pd.read_csv('../data/news_dataset.zip', compression='zip') 
data.head()

,text,label,text_es
0,"Here s the fake black guy, Shaun King weighing...",0,"Aquí está el falso negro, Shaun King, pensando..."
1,A Tennessee Trump supporter is ecstatic that O...,0,Una defensora de Tennessee Trump está extasiad...
2,Join Patrick every week here at 21WIRE.TV for ...,0,Únete a Patrick cada semana aquí en 21WIRE.TV ...
3,This is what happens when racists don t get th...,0,Esto es lo que sucede cuando los racistas no c...
4,WASHINGTON (Reuters) - U.S. President Donald T...,1,WASHINGTON (Reuters) - El presidente estadouni...

In [5]:
#Buscar nulos y duplicados 
print("Nulos:\n",data.isnull().sum())
print("Duplicados: ",data.duplicated().sum())

#Eliminar duplicados 
data.drop_duplicates(inplace=True) 
print("Duplicados: ",data.duplicated().sum())

Nulos:
 text       0
label      0
text_es    0
dtype: int64
Duplicados:  0
Duplicados:  0

In [11]:
#Procesar en chunks 
chunk_size = 5000  # Cambia según tu RAM
textos = list(data['text_es'])
limpiar_textos = []

print("Procesando textos en chunks")
for i in range(0, len(textos), chunk_size):
    chunk = textos[i:i+chunk_size]
    limpiar_chunk = limpieza(chunk)
    limpiar_textos.extend(limpiar_chunk)
#Aplicar limpieza
print(limpiar_textos[124:127])

Procesando textos en chunks
[['presidente', 'electo', 'donald', 'trump', 'llamar', 'tsai', 'presidente', 'taiwán', 'pequeño', 'acción', 'taiwán', 'ministro', 'chino', 'relaciones', 'exteriores', 'wang', 'yi', 'sábado', 'phoenix', 'television', 'sede', 'hong', 'kong', 'conversación', 'contacto', 'tipo', 'taiwán', 'presidente', 'electo', 'presidente', 'jimmy', 'carter', 'cambiar', 'reconocimiento', 'diplomático', 'taiwán', 'chino', 'reconocer', 'taiwán', 'china', 'taiwanés', 'participar', 'acción', 'mezquino', 'cambiar', 'estructura', 'china', 'formado', 'comunidad', 'internacional', 'wang', 'foro', 'académico', 'estación', 'cambiar', 'política', 'chino', 'largo', 'data', 'gobierno', 'estados', 'unidos', 'principio', 'chino', 'piedra', 'angular', 'sano', 'desarrollo', 'vínculo', 'esperar', 'base', 'político', 'interferir', 'gobierno', 'china', 'dañar'], ['movimiento', 'precedente', 'historia', 'estados', 'unidos', 'republicano', 'controlar', 'senado', 'simplemente', 'negar', 'tomar', 'medida', 'candidatura', 'presidente', 'barack', 'obama', 'garland', 'trabajo', 'vida', 'corte', 'superior', 'nación', 'senado', 'votar', 'confirmar', 'brandeis', 'convertir', 'justicia', 'judío', 'estados', 'unidos', 'constitución', 'estados', 'unidos', 'asignar', 'senado', 'confirmar', 'candidatura', 'presidente', 'corte', 'superior', 'presidente', 'junta', 'ejecutivo', 'presentar', 'junta', 'ejecutivo', 'junta'], ['caso', 'junta', 'representante', 'junta']]

In [12]:
textos_limpios_str = [" ".join(tokens) for tokens in limpiar_textos]

In [13]:
data_limpio = pd.DataFrame({
    'text_limpio': textos_limpios_str,
    'label': data['label'].values
})
data_limpio.to_csv("../data/dataset_limpio.csv", index=False, encoding='utf-8')
data_limpio.head()

                                         text_limpio  label
0  falso negro shaun king pensar impresionante be...      0
1  defensora tennessee trump extasiado obamacare ...      0
2  únetir patrick semana 21wire.tv obtener notici...      0
3  suceder racista donald trump enfureceír base r...      0
4  washington reuters presidente estadounidense d...      1