In [2]:
import spacy
import pandas as pd
nlp = spacy.load("es_core_news_md")

Pre procesamiento

In [3]:
def limpieza_mejorada(textos):
    resultados = []
    textos = [texto.lower() for texto in textos]
    
    for doc in nlp.pipe(textos, batch_size=1000):
        palabras = []
        for token in doc:
            # Filtrar tokens NO deseados
            if (
                token.is_alpha                          # solo letras
                and not token.is_stop                   # sin stopwords
                and len(token.lemma_) > 1               # sin tokens de 1 letra
                and token.pos_ != "PROPN"               # elimina nombres propios
                and token.lemma_.isalpha()              # evita lemas con símbolos
                and len(token.lemma_) <= 20             # evita palabras "basura" muy largas
            ):
                palabras.append(token.lemma_)
        resultados.append(palabras)
    return resultados

In [4]:
data = pd.read_csv('../data/news_dataset.zip', compression='zip') 
data.head()

,text,label,text_es
0,"Here s the fake black guy, Shaun King weighing...",0,"Aquí está el falso negro, Shaun King, pensando..."
1,A Tennessee Trump supporter is ecstatic that O...,0,Una defensora de Tennessee Trump está extasiad...
2,Join Patrick every week here at 21WIRE.TV for ...,0,Únete a Patrick cada semana aquí en 21WIRE.TV ...
3,This is what happens when racists don t get th...,0,Esto es lo que sucede cuando los racistas no c...
4,WASHINGTON (Reuters) - U.S. President Donald T...,1,WASHINGTON (Reuters) - El presidente estadouni...

In [5]:
#Buscar nulos y duplicados 
print("Nulos:\n",data.isnull().sum())
print("Duplicados: ",data.duplicated().sum())

#Eliminar duplicados 
data.drop_duplicates(inplace=True) 
print("Duplicados: ",data.duplicated().sum())

Nulos:
 text       0
label      0
text_es    0
dtype: int64
Duplicados:  0
Duplicados:  0

In [6]:
#Procesar en chunks 
chunk_size = 5000  # Cambia según tu RAM
textos = list(data['text_es'])
limpiar_textos = []

print("Procesando textos en chunks")
for i in range(0, len(textos), chunk_size):
    chunk = textos[i:i+chunk_size]
    limpiar_chunk = limpieza_mejorada(chunk)
    limpiar_textos.extend(limpiar_chunk)
#Aplicar limpieza
print(limpiar_textos[:5])

Procesando textos en chunks

KeyboardInterrupt:

In [ ]:
textos_limpios_str = [" ".join(tokens) for tokens in limpiar_textos]

In [ ]:
data_limpio = pd.DataFrame({
    'text_limpio': textos_limpios_str,
    'label': data['label'].values
})
data_limpio.to_csv("../data/dataset_limpio.csv", index=False, encoding='utf-8')
data_limpio.head()

                                         text_limpio  label
0  donald trump white house chaos try cover russi...      0
1  donald trump presumptive gop nominee time reme...      0
2  mike pence huge homophobe support ex gay conve...      0
3  san francisco reuters california attorney gene...      1
4  twisted reasoning come pelosi day especially p...      0